### ISSUE TITLE
Rounding and Type Change methods

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/stdsimd#23]
Before we can begin implementing a few of the more advanced functions, we'll need a few more of the basic utility functions for manipulating values.

For floats:
* [ ] round to nearest whole number (output is the same float type)
* [ ] ceiling / round to infinity
* [ ] floor / round to negative infinity
* [ ] truncate / round to zero
* [ ] fraction (remove the whole-number part)
* [ ] round to integer (output is the same-bit signed integer type)

For signed ints:
* [ ] round to float (output is the same-bit float type)

**Comment by calebzulawski** [comment]
Any idea what the type converting functions should be called?  There doesn't seem to be an equivalent for `f32` or `f64`...

**Comment by Lokathor** [comment]
in wide i call them `round` and then `round_int`.

basically https://doc.rust-lang.org/core/arch/x86_64/fn._mm_cvtps_epi32.html

**Comment by calebzulawski** [comment]
Probably relevant: https://doc.rust-lang.org/std/intrinsics/fn.float_to_int_unchecked.html

There actually is an equivalent in std but I missed it.

**Comment by Lokathor** [comment]
I think that cvtps_epi32 returns *a value* for any value, even if the value is not the same number. I think that nans produce i32::MIN or something like that.

I'd hate to add more ways to get undef, but i suppose it could be done if that's what the people clamor for.

**Comment by calebzulawski** [comment]
Well, on a failure it raises a fp exception still (NEON's `vcvt` does this as well).  I think the function should be unsafe because we the output is undefined on those lanes (but if we specify it's only undefined on those lanes, I think it's easy enough to use, even if it's unsafe?)
