### ISSUE TITLE
Improve contributor docs to minimum

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/stdsimd#24]
- [x] Draft a CONTRIBUTING.md
- [x] Encourage chunking tasks
- [ ] Create an issue template?
- [x] Link to Zulip
- [x] Link to FAQ
- [ ] Cross-link docs / adopt orphans where feasible
